### ISSUE TITLE
How to include fields that have subfields

### ISSUE THREAD

**Issue by ibrahimlawal** [rkbalgi/isosim#2]
Hey boss,

Nifty stuff you wrote here.

Please how do I represent fields that have subfields  when writing a spec? `127.2` for instance.

Thanks!

**Comment by rkbalgi** [comment]
Hey Ibrahim, At the moment, there is no such capability. Again, it can be implemented - it might be simple if sub fields are all fixed else can be complex. Feel free to fork! :-)
