### ISSUE TITLE
Packages Not Found

### ISSUE THREAD

**Issue by mdennnism** [rkbalgi/isosim#3]
I tried running the compile for the app and got hit with errors regarding the import referencing which result to github.com/rkbalgi folder. I updated this to match my src folder. However this resulted in many more packages referencing not finding files. I have updated the files and the issues keep on arising as some files are not even in this github repo. Kindly check.
Last error received:
`work/src/my_project/isosim/web/http_handlers/save_msg_handler.go:4:2: cannot find package "github.com/rkbalgi/isosim/data" in any of:
        /usr/local/go/src/github.com/rkbalgi/isosim/data (from $GOROOT)
        /home/munyuamugambi/work/src/github.com/rkbalgi/isosim/data (from $GOPATH)
work/src/my_project/isosim/web/http_handlers/isoserv_handlers/active_servers.go:5:2: cannot find package "github.com/rkbalgi/isosim/iso_server" in any of:
        /usr/local/go/src/github.com/rkbalgi/isosim/iso_server (from $GOROOT)
        /home/munyuamugambi/work/src/github.com/rkbalgi/isosim/iso_server (from $GOPATH)
work/src/my_project/isosim/web/http_handlers/all_specs_handler.go:5:2: cannot find package "github.com/rkbalgi/isosim/web/spec" in any of:
        /usr/local/go/src/github.com/rkbalgi/isosim/web/spec (from $GOROOT)
        /home/munyuamugambi/work/src/github.com/rkbalgi/isosim/web/spec (from $GOPATH)
work/src/my_project/isosim/web/http_handlers/parse_trace_handler.go:9:2: cannot find package "github.com/rkbalgi/isosim/web/ui_data" in any of:
        /usr/local/go/src/github.com/rkbalgi/isosim/web/ui_data (from $GOROOT)
        /home/munyuamugambi/work/src/github.com/rkbalgi/isosim/web/ui_data (from $GOPATH)
work/src/my_project/isosim/web/http_handlers/misc_handlers/misc_handler.go:5:2: cannot find package "go/hsm" in any of:
        /usr/local/go/src/go/hsm (from $GOROOT)
        /home/munyuamugambi/work/src/go/hsm (from $GOPATH)
work/src/my_project/isosim/web/http_handlers/send_msg_handler.go:15:2: cannot find package "go/net" in any of:
        /usr/local/go/src/go/net (from $GOROOT)
        /home/munyuamugambi/work/src/go/net (from $GOPATH)
/usr/local/go/src/go/encoding/ascii.go:18:2: cannot find package "golang.org/x/text/encoding" in any of:
        /usr/local/go/src/vendor/golang.org/x/text/encoding (vendor tree)
        /usr/local/go/src/golang.org/x/text/encoding (from $GOROOT)
        /home/munyuamugambi/work/src/golang.org/x/text/encoding (from $GOPATH)
/usr/local/go/src/crypto/tls/cipher_suites.go:18:2: cannot find package "golang_org/x/crypto/chacha20poly1305" in any of:
        /usr/local/go/src/vendor/golang_org/x/crypto/chacha20poly1305 (vendor tree)
        /usr/local/go/src/golang_org/x/crypto/chacha20poly1305 (from $GOROOT)
        /home/munyuamugambi/work/src/golang_org/x/crypto/chacha20poly1305 (from $GOPATH)
/usr/local/go/src/crypto/x509/x509.go:36:2: cannot find package "golang_org/x/crypto/cryptobyte" in any of:
        /usr/local/go/src/vendor/golang_org/x/crypto/cryptobyte (vendor tree)
        /usr/local/go/src/golang_org/x/crypto/cryptobyte (from $GOROOT)
        /home/munyuamugambi/work/src/golang_org/x/crypto/cryptobyte (from $GOPATH)
/usr/local/go/src/crypto/x509/x509.go:37:2: cannot find package "golang_org/x/crypto/cryptobyte/asn1" in any of:
        /usr/local/go/src/vendor/golang_org/x/crypto/cryptobyte/asn1 (vendor tree)
        /usr/local/go/src/golang_org/x/crypto/cryptobyte/asn1 (from $GOROOT)
        /home/munyuamugambi/work/src/golang_org/x/crypto/cryptobyte/asn1 (from $GOPATH)
/usr/local/go/src/crypto/tls/key_agreement.go:20:2: cannot find package "golang_org/x/crypto/curve25519" in any of:
        /usr/local/go/src/vendor/golang_org/x/crypto/curve25519 (vendor tree)
        /usr/local/go/src/golang_org/x/crypto/curve25519 (from $GOROOT)
        /home/munyuamugambi/work/src/golang_org/x/crypto/curve25519 (from $GOPATH)
/usr/local/go/src/net/http/h2_bundle.go:47:2: cannot find package "golang_org/x/net/http2/hpack" in any of:
        /usr/local/go/src/vendor/golang_org/x/net/http2/hpack (vendor tree)
        /usr/local/go/src/golang_org/x/net/http2/hpack (from $GOROOT)
        /home/munyuamugambi/work/src/golang_org/x/net/http2/hpack (from $GOPATH)
/usr/local/go/src/net/http/h2_bundle.go:48:2: cannot find package "golang_org/x/net/idna" in any of:
        /usr/local/go/src/vendor/golang_org/x/net/idna (vendor tree)
        /usr/local/go/src/golang_org/x/net/idna (from $GOROOT)
        /home/munyuamugambi/work/src/golang_org/x/net/idna (from $GOPATH)
/usr/local/go/src/net/http/h2_bundle.go:49:2: cannot find package "golang_org/x/net/lex/httplex" in any of:
        /usr/local/go/src/vendor/golang_org/x/net/lex/httplex (vendor tree)
        /usr/local/go/src/golang_org/x/net/lex/httplex (from $GOROOT)
        /home/munyuamugambi/work/src/golang_org/x/net/lex/httplex (from $GOPATH)
/usr/local/go/src/net/http/transport.go:32:2: cannot find package "golang_org/x/net/proxy" in any of:
        /usr/local/go/src/vendor/golang_org/x/net/proxy (vendor tree)
        /usr/local/go/src/golang_org/x/net/proxy (from $GOROOT)
        /home/munyuamugambi/work/src/golang_org/x/net/proxy (from $GOPATH)`

**Comment by rkbalgi** [comment]
I've put up a small wiki page here with an example - https://github.com/rkbalgi/isosim/wiki/Setting-Up

**Comment by mdennnism** [comment]
Thanks rkbalgi. It is working ok.
