### ISSUE TITLE
Support MLI Type 4E

### ISSUE THREAD

**Issue by Josephu** [rkbalgi/isosim#51]
I am currently working on an integration in which the MLI type is 4E. I have already branched out to do my first attempt. Unfortunately given home page is not working, I can't test if the test examples still work with my change.

https://github.com/rkbalgi/go/pull/8

**Comment by rkbalgi** [comment]
I have included your changes and the latest changes are on master, please have a go. (BTW, I have renamed the github.com/rkbalgi/go repo to a slightly better github.com/rkbalgi/libiso). I have done brief little testing with 4E and it seems to work fine.

**Comment by Josephu** [comment]
Thank you so much, you are so efficient!
