### ISSUE TITLE
The yaml format spec is not working

### ISSUE THREAD

**Issue by Josephu** [rkbalgi/isosim#53]
I have been using the yaml format spec and after the new release it seemed broken. I can replicate it with your example in test/testdata/specs/iso_specs.yaml and that did not work as well.

To replicate it, you go to the server page, load an existing definition, then you will notice the message types will not show up in the loaded definition. If you use "Msg selector" same issue will happen. It works fine with test/testdata/specs/isoSpecs.spec though.

**Comment by Josephu** [comment]
Sorry looks like the issue is related to browser storage. After I clear my browser storage, things seem to be normal again.

**Comment by rkbalgi** [comment]
Can you try changing the spec to a another spec and then go back to the original spec again? And then load a definition. The issue was that messages were getting loaded only on spec change.  I thought I had fixed this one..Let me know if it goes away.

**Comment by rkbalgi** [comment]
Closing these for now, please open if needed.

**Comment by Josephu** [comment]
I have just tested the latest version `v0.10.0`, and this issue does not seem to exist anymore.

I also noticed you incorporated 4E and 4I into the simulator, which is a great help for me, thank you so much!
