### ISSUE TITLE
Nested Fields definition examples are missing

### ISSUE THREAD

**Issue by moisoto** [rkbalgi/isosim#7]
There's a disclaimer saying that nested fields are only supported for bitmapped fields.

But I don't see any example of Nested fields in the specs file. Can you provide example(s) of how to define nested fields, even if they are only bitmapped?

Also is there any plan to allow nested fields of other types?

**Comment by rkbalgi** [comment]
What I meant I think was - In a sense, all the fields in a ISO message are subfields of the bitmap (although they're not embedded inside it). I will look at including support for nested fields in next few days. Thanks.

**Comment by rkbalgi** [comment]
src/github.com/rkbalgi/isosim/iso/iso_msg_parse_test.go and src/github.com/rkbalgi/isosim/iso/iso_msg_assemble_test.go have examples of nested/embedded fields (branch release/v2020.03)

**Comment by rkbalgi** [comment]
The fixes are now available on master
