### ISSUE TITLE
Offset values not working

### ISSUE THREAD

**Issue by JoVzla** [rkbalgi/isosim#70]
Adding Offset fields in ProcessingConditions isn't working,

The code use:
**iso_server.html**
`516:  setFieldOff(msgSelectionConditionId, obj, fieldsHtml);`

and it should be 
`516: setFieldOff(msgSelectionConditionId, obj.FieldId, fieldsHtml);`

EDIT: solution tested and working

tested with:

```
"ProcessingConditions": [
                {
                    "OffFields": [
                        {
                            "FieldId": 3
                        }
                    ],
```

PR done.

**Comment by JoVzla** [comment]
You are right, sorry. Closing Issue.

**Comment by rkbalgi** [comment]
No problem!
