### ISSUE TITLE
Error= isosim: SSL enabled, but certificate/key file unspecified.

### ISSUE THREAD

**Issue by mehrdad2000** [rkbalgi/isosim#76]
I try to run [docker edition](https://hub.docker.com/r/rkbalgi/isosim) of ISO WebSim, but get below error:

Failed to start ISO WebSim. Error= isosim: SSL enabled, but certificate/key file unspecified.

any idea?

![8B1B1143-7396-464F-B351-3B71061898D7](https://user-images.githubusercontent.com/26499665/183072878-75f1566e-9c27-4189-8f85-292b6b414294.jpeg)

**Comment by ss185427** [comment]
Getting the same error on running `docker run -d -p 8080:8080 rkbalgi/isosim:latest`.
Running docker inspect shows "TLS_ENABLED=false".

**Comment by rkbalgi** [comment]
> Getting the same error on running `docker run -d -p 8080:8080 rkbalgi/isosim:latest`.
> 
> Running docker inspect shows "TLS_ENABLED=false".

Hi @ss185427, I will take a look. Thanks

**Comment by rkbalgi** [comment]
@ss185427 Can you pull up the latest image and try?

**Comment by rkbalgi** [comment]
@mehrdad2000 FYI ..

**Comment by ss185427** [comment]
> @ss185427 Can you pull up the latest image and try?

@rkbalgi error is fixed now, thank you.
